# Generated by Django 2.2.1 on 2019-09-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=5)),
                ('companyName', models.CharField(max_length=200)),
                ('emailAddress', models.CharField(max_length=200)),
            ],
        ),
    ]
